/* ============================================================
   SONGDO TIMES — content data
   A monthly city magazine, reported by Songdo's students.

   To publish a new issue: add an entry to ISSUES (newest first)
   and add that month's articles to ARTICLES with issue: "YYYY-MM".
   The home page automatically features the newest issue.

   Article `body` is an array of blocks:
     "text"                       → a paragraph
     { p: "text" }                → a paragraph
     { h: "Subtitle" }            → a section subtitle
     { qa: [{q,a}, ...] }         → an interview
     { steps: ["...", ...] }      → a numbered how-to
     { places: [{name,addr,hours,note}] } → location cards
     { note: "text" }             → a small footnote / sources line
   ============================================================ */

window.FOUNDER = {
  name: "A Letter from the Editors",
  nameKo: "에디터의 편지",
  role: "Founder's Note",
  photo: "The young writers of Songdo Times — group portrait",
  bio: [
    { en: "Songdo is home to a remarkable number of people from around the world. International schools, global campuses, foreign-invested companies, and families who have moved here from abroad all share these streets. Yet so much of the news and information about this city is written only in Korean — and rarely for them.",
      ko: "송도에는 정말 많은 외국인들이 살고 있습니다. 국제학교, 글로벌 캠퍼스, 외국계 기업, 그리고 해외에서 이주해 온 가족들이 이 거리를 함께 나눕니다. 하지만 이 도시에 관한 뉴스와 정보의 대부분은 한국어로만, 그것도 그들을 위한 것이 아닌 채로 쓰여 있습니다." },
    { en: "We started Songdo Times to deliver living, useful stories for those neighbors — the people who need to know this city in a language they can read. Where to study, what to eat, how the city is changing, what is happening this spring: the things you only learn by actually living here.",
      ko: "Songdo Times는 그런 이웃들을 위해, 그들이 읽을 수 있는 언어로 살아있고 유용한 이야기를 전하고 싶어 시작했습니다. 어디서 공부하고, 무엇을 먹고, 도시가 어떻게 변하고, 이번 봄에 무슨 일이 열리는지 — 직접 살아봐야 알 수 있는 것들을 담습니다." },
    { en: "We are students who have lived in Songdo, and who keep living here. We grow up inside this city, walk its streets every day, and notice the things that guidebooks miss. As Songdo's own students, we want to report Songdo's news — for everyone who calls this place home.",
      ko: "우리는 송도에 살아왔고, 지금도 계속 송도에 살고 있는 학생들입니다. 이 도시 안에서 자라고, 매일 이 거리를 걷고, 안내서가 놓치는 것들을 발견합니다. 송도의 학생으로서, 우리는 이곳을 집이라 부르는 모든 사람을 위해 송도의 뉴스를 전하고 싶습니다." },
    { en: "Every issue is a first draft of Songdo's history, written by its newest citizens.",
      ko: "모든 호는 이 도시의 가장 새로운 시민들이 쓰는, 송도 역사의 첫 번째 초고입니다." },
  ],
  team: [
    { name: "Grace Somang Yoo", role: "Reporter" },
    { name: "Jei Jang", role: "Reporter" },
    { name: "Hannah Lee", role: "Reporter" },
    { name: "Youngho Shin", role: "Reporter" },
    { name: "Roy Kim", role: "Reporter" },
    { name: "Zoe Kim", role: "Reporter" },
    { name: "Lianne Kang", role: "Reporter" },
    { name: "Christina Jang", role: "Reporter" },
    { name: "Seowoo Park", role: "Reporter" },
    { name: "Jooa Park", role: "Reporter" },
    { name: "Jake Jeon", role: "Reporter" },
    { name: "Jason Song", role: "Reporter" },
  ],
  sign: "— The Editors, Songdo Times",
};

window.ISSUES = [
  { id: "2026-09", month: "September", monthShort: "Sep", year: 2026, no: 4,
    theme: "How Songdo Lives",
    note: "Famous faces on convenience-store shelves, a world of food by the academies, and the bikes that fill every street \u2014 the everyday habits of a city." },
  { id: "2026-05", month: "May", monthShort: "May", year: 2026, no: 3,
    theme: "The Outside In",
    note: "Viral convenience-store snacks, a distant strait moving fuel prices, a new ruling on international schools \u2014 the wider world, felt on Songdo's streets this month." },
  { id: "2026-04", month: "April", monthShort: "Apr", year: 2026, no: 2,
    theme: "The Study City",
    note: "Inside the academies that shape a student city — how Songdo learns after the last school bell." },
  { id: "2026-03", month: "March", monthShort: "Mar", year: 2026, no: 1,
    theme: "Tastes & Tracks",
    note: "A viral dessert and a high-speed railway: the two things Songdo couldn't stop talking about this month." },
];

window.ARTICLES = [
  // ===== SEPTEMBER 2026 (current) =====
  {
    id: "sep-cvs", issue: "2026-09", featured: true,
    cat: "Food",
    title: "Why Convenience Stores Bet on Famous Faces",
    author: "Roy Kim & Youngho Shin", org: "Chadwick International School",
    date: "Sep 22, 2026", read: 6,
    img: "images/sep-cvs-cover.jpg",
    photo: "This month's convenience-store deals, from fried chicken to chef-branded bibimbap",
    dek: "Step outside any building in Korea and there is a convenience store. With so many products competing for attention, stores have found a way to stand out: celebrities and famous chefs. Does it actually work?",
    body: [
      { p: "Every time you step outside of a building in Korea, you can see a convenience store. Chains like CU, GS25, Emart24, and 7-Eleven offer an enormous range of foods and products. With so many choices overflowing from the shelves, stores must find a way to stand out and attract customers. One famous way is by partnering with people such as celebrities and famous chefs. It makes customers more curious about a product \u2014 and more willing to try it." },
      { h: "Attention and trust" },
      { p: "One reason convenience stores use celebrities is that famous people attract attention and build trust. Customers are more interested in a product when it is connected to someone they already know and like. A chef collaboration can make a product feel trustworthy, because people believe the chef knows food well. After the TV program \u201cCulinary Class Wars,\u201d for example, chef Kwon Sung-jun (Napoli Mafia) collaborated on many products with CU, helping the chain's sales. JoongAng Ilbo has also reported that food made by famous chefs makes customers feel it is more reliable." },
      { gallery: [
        { img: "images/sep-a-5.jpg", cap: "Jeonju-style Beef Bibimbap \u2014 3,520 won" },
        { img: "images/sep-a-6.jpg", cap: "Special Soy Sauce Autumn Radish Bibimbap \u2014 3,900 won" },
        { img: "images/sep-a-7.jpg", cap: "Special Soybean Paste Bulgogi Bibimbap \u2014 3,900 won" },
      ] },
      { h: "300,000 lunchboxes in two weeks" },
      { p: "A good example is the collaboration between singer Sung Si-kyung and a convenience-store lunchbox, released on September 2, 2026. According to Financial Post, it sold roughly 300,000 units in only two weeks, becoming the number-one lunchbox at the time \u2014 sales estimated at around 350\u2013400 million won. The collaboration clearly drew customers in quickly." },
      { p: "Still, sales numbers alone cannot prove that Sung Si-kyung was the reason for the success. The taste, price, design, and popularity of the lunchbox itself could also have played a part. Even so, how fast and how much it sold after release shows that a famous face can be an effective way to bring attention to a convenience-store product." },
      { p: "As one shopper put it: \u201cIf a chef made it, I trust it more \u2014 so I like it.\u201d" },
      { h: "On the shelves this month" },
      { p: "Beyond the lunchboxes, this month's shelves are full of discounted picks \u2014 whole fried chicken, crispy boneless nuggets, a hot-chili mozzarella stick, and chicken skewers. There are even KBO baseball uniforms and caps at steep discounts, plus instant noodles and snacks such as Jjapaghetti, Samyang Ramen, and Kkokkalcorn." },
      { gallery: [
        { img: "images/sep-a-1.jpg", cap: "Whole Fried Chicken \u2014 10,320 won with Naver Pay" },
        { img: "images/sep-a-2.jpg", cap: "Crispy Boneless Chicken Nuggets \u2014 7,920 won with Naver Pay" },
        { img: "images/sep-a-3.jpg", cap: "Hot Chili Whole Mozzarella Stick \u2014 2,900 won" },
        { img: "images/sep-a-4.jpg", cap: "Boneless / Spicy Chicken Skewer \u2014 2,300 won" },
        { img: "images/sep-a-8.jpg", cap: "KBO uniforms \u2014 105,000 \u2192 29,400 won" },
        { img: "images/sep-a-9.jpg", cap: "KBO caps \u2014 36,000 \u2192 9,720 won" },
        { img: "images/sep-a-10.jpg", cap: "Jjapaghetti, Samyang Ramen, Kkokkalcorn" },
      ] },
      { note: "Sources: JoongAng Ilbo, Seoul Economic Daily, Asia Economy, Financial Post; product prices from 7-Eleven event listings." },
    ],
  },
  {
    id: "sep-cuisine", issue: "2026-09",
    cat: "City",
    title: "A World of Flavors by the Academy District",
    author: "Lianne Park, Seowoo Park & Zoe Kim", org: "Chadwick International School",
    date: "Sep 15, 2026", read: 6,
    img: "images/sep-b-1.jpg",
    photo: "Songdo's resident population by year, 2019\u20132024",
    dek: "Korean, Japanese, Italian, Vietnamese, Thai, Mexican \u2014 the streets around Songdo's academies serve the world. Why is the food here so diverse, and what does it mean for the people who live here?",
    body: [
      { h: "Why so many cuisines?" },
      { p: "Songdo has diverse cuisines because it is a modern, international area with many foreign residents. The number of foreign residents has grown since 2019, bringing people from many cultural backgrounds and countries \u2014 and with them, demand for many kinds of food. Songdo is also home to international schools, and sits close to Incheon Airport." },
      { h: "The most international of the three" },
      { p: "Among Korea's three international cities \u2014 Cheongna, Yeongjongdo, and Songdo \u2014 Songdo has the most foreign residents. According to IFEZ (Incheon Free Economic Zone) data, Songdo has consistently had a comparatively high number of foreign residents for the past six years. In 2026, 6,051 foreigners live in Songdo: about three times as many as in Yeongjongdo, and roughly five times as many as in Cheongna, which has only 1,422. Foreigners make up 2.8% of Songdo's population, compared with 2.2% in the other cities." },
      { fig: { img: "images/sep-b-2.jpg", cap: "Resident and foreign-resident figures for Songdo, Yeongjongdo, and Cheongna, 2020\u20132026 (IFEZ)." } },
      { p: "International schools and universities play a big role in that number \u2014 but the government's actions show how much food matters too. It is pushing for every restaurant and café in the city to offer an English menu and to accept foreign currencies for travelers. Songdo's two international schools, Chadwick International and Calvin Manitoba International School, sit far apart, so foreign families live spread across the whole city \u2014 which helps explain why restaurants of every kind appear all over Songdo." },
      { h: "What residents told us" },
      { p: "To find out, we interviewed eight people living near the academy district \u2014 four students and four adults. Asked which restaurant they like most, the students named places like Beomuri, Yoharu, Mitaly, Banwoo-dong, and Kimbap Heaven: tteokbokki, pork cutlet, pasta, pizza, ramen, and udon. Jooa especially loves the pasta at Mitaly. The adults chose Deojinguk, Bongibab, J Sushi, and Sosodam \u2014 mostly Korean dishes and comfort food. Students leaned toward casual, hearty food; adults toward comforting meals." },
      { p: "Everyone had tried several cuisines in Songdo \u2014 Korean, Italian, Japanese and more \u2014 and one student said he had tried many different kinds. Asked what they'd like to see more of, most were happy with what exists, but one student asked for more Japanese restaurants: beyond sushi, udon, and pork cutlet, he wants a wider range." },
      { p: "In the end, the variety of cuisine \u2014 together with schools, the airport, and the city's international ambitions \u2014 has helped Songdo become a more diverse place, with more foreign residents calling it home." },
      { note: "Data: IFEZ (Incheon Free Economic Zone) resident statistics." },
    ],
  },
  {
    id: "sep-bikes", issue: "2026-09",
    cat: "City",
    title: "Why Songdo Rides",
    author: "Jooa Park & Christina Jung", org: "Chadwick International School",
    date: "Sep 8, 2026", read: 6,
    img: "images/sep-c-3.jpg",
    photo: "Songdo Central Park from above \u2014 tree-lined paths divided for walkers and cyclists",
    dek: "Bikers fill Songdo's streets day and night \u2014 students heading to school and academies, commuters, families in the park. What makes this city so easy to ride, and how does it change the people who live here?",
    body: [
      { p: "Bikers fill the streets of Songdo all day and night. Whether students are biking to school and after-school academies or people use bikes as their main way to get around, Songdo offers an efficient biking environment for daily life. Roads carry white bike-shaped markings, and schools and public places have rows and rows of bike racks. It is safe to say Songdo makes biking easy, accessible, and enjoyable. So what exactly makes biking one of its biggest forms of transport \u2014 and how does it affect its citizens?" },
      { h: "Roads that make sense" },
      { fig: { img: "images/sep-c-1.jpg", cap: "Fig. 1 \u2014 A separated bike lane right outside a school." } },
      { p: "Roads in Songdo are clearly split between pedestrians and bikers, with a bike illustration printed on the cycling side. These roads are everywhere \u2014 right outside people's homes and near schools. Figure 1, taken outside a school, shows how clearly the lane tells bikers where to ride, so neither walkers nor riders have to navigate confusing, overlapping paths. The marking is visually simple \u2014 no words, just a picture \u2014 so anyone can understand it." },
      { h: "A rack on every corner" },
      { fig: { img: "images/sep-c-2.jpg", cap: "Fig. 2 \u2014 Bike racks inside Chadwick International School Songdo." } },
      { p: "Figure 2 shows a bike rack inside Chadwick International School, where students park during school hours. But racks aren't only at schools \u2014 they sit in front of public buildings, in parks, and more. It's no exaggeration to say they are everywhere in Songdo. With a rack always nearby, riders don't have to worry about where to store their bikes safely, which makes choosing a bike that much easier." },
      { h: "A city planned for green" },
      { p: "When Songdo was first established, it was designed as an environmentally friendly, planned community \u2014 and eco-friendly parks were a central part of that. Songdo has 13 public parks, all with well-managed cycling paths. In Central Park, most roads are clearly divided for pedestrians and cyclists, preventing accidents and keeping the park comfortable. The park even rents family bikes for four or more people who want to enjoy the breeze." },
      { p: "As figure 3 shows, the park is lined with trees and structures that make the walkways beautiful and shade walkers and picnickers. As a planned community, Songdo was built to spread out large populations, support industry, and provide housing \u2014 which meant designing a city that could function sustainably and make the most of its space." },
      { h: "Who rides, and why it matters" },
      { p: "Look out the window of any building in Songdo and you'll see bikers of every age. For teenagers, cycling has become a way to bond: boys around 13 to 16 ride near schools and convenience stores after school and before academies, and girls regularly bike to school, to activities, and through the parks. Beyond physical health, cycling helps mentally too \u2014 a short break outside, away from academics and stress, can help prevent the depression and anxiety that are common in Korea." },
      { p: "Ultimately, Songdo gives its citizens a well-built environment to enjoy: managed bike roads, easy-to-reach racks, and parks found throughout the city. Together they open people up to new hobbies like biking \u2014 good for their health, and for the everyday stress of a fast-changing society." },
    ],
  },

  {
    id: "sep-glass", issue: "2026-09",
    cat: "Opinion",
    title: "An Island Made of Glass",
    author: "Jake Jeon", org: "Songdo Times",
    date: "Sep 29, 2026", read: 8,
    img: "images/IMG_0747.jpg",
    photo: "Songdo's glass towers rising above Central Park",
    dek: "How to live in the most beautiful city while feeling like you live in the smallest one.",
    body: [
      { p: "Songdo is a well-designed city. I do not mean that sarcastically." },
      { p: "Its roads stretch out in neat grids. At night, entire walls of glass on high-rise buildings light up. Parks and waterways are within walking distance. People who move here for the first time are usually impressed. Relatives who visit are impressed, too. I have heard, \u201cThis place is really nice,\u201d more times than I can count." },
      { p: "The problem is that living in Songdo as a teenager is an entirely different experience from visiting it." },
      { h: "If you stay in, there is nothing to do. If you go out, it takes all day." },
      { p: "Suppose you want to see an exhibition on the weekend. Seoul is about an hour and a half away each way. You take Line 1, transfer, then transfer again. By the time you have spent three hours traveling there and back, you may have spent more time sitting on the subway than actually looking at the exhibition." },
      { p: "On a weekday, you do not even consider going." },
      { p: "I remember one Saturday when a friend and I decided, almost impulsively, that we should go into Seoul. We had been talking about an exhibition for weeks, and that morning we finally said, \u201cWhy not today?\u201d So we met at the subway station. We checked the route. We calculated the transfers. We looked at the time. Then we realized we would not get home until late afternoon." },
      { p: "Neither of us had anything particularly urgent to do. That was the strange part. We were not busy. We just did not want to spend six hours of our Saturday getting somewhere and coming back. We stood there for a few minutes, looking at the train map on the wall." },
      { p: "\u201cMaybe next weekend,\u201d one of us said. We went to a caf\u00e9 instead." },
      { p: "Nothing dramatic happened. No great disappointment, no argument, no particular moment worth remembering. And somehow, that is exactly what I remember." },
      { p: "So your plans get smaller. At first, it is, \u201cLet's go next weekend.\u201d Then, \u201cLet's go after exams.\u201d Eventually, you stop going altogether. What remains is school, home, and Triple Street. Years pass inside the triangle connecting those three points." },
      { p: "It is not that Songdo has nowhere to go. There are plenty of caf\u00e9s. The shopping centers are clean and convenient. But that is about it. There are few live music venues, independent bookstores, or strange little shops you happen to stumble upon by accident. That is the honest downside of a planned city: things that were not planned rarely seem to exist." },
      { h: "Growing up in a place with zero anonymity" },
      { p: "The bigger problem, however, is social." },
      { p: "The international-school community in Songdo is small. You see many of the same faces from kindergarten through twelfth grade. Six years. For some people, ten. Who is dating whom, who is applying to which university, who got rejected from where \u2014 by the next day, the entire grade knows. Parents know each other, too. Information travels from school to home, and from home back to school, making a full circle within a day." },
      { p: "You do not really understand why this matters until you experience it. The key problem is the lack of a chance to start over." },
      { p: "For most teenagers, moving from middle school to high school, and later from high school to college, gives them opportunities to redefine themselves. Something embarrassing you did in eighth grade may never follow you into a new school because nobody there knows about it. Here, there is no such reset. A nickname you got in elementary school can follow you until senior year. Once you become \u201cthat kid who is just like that,\u201d there may be no stage on which to prove otherwise." },
      { p: "So many students quietly learn to be careful. They avoid standing out. They hesitate to try something new. If they think they might fail, they sometimes decide not to start at all. In a community where failure can become part of your permanent reputation, that is a rational choice." },
      { p: "It is just a rather sad kind of rationality for a sixteen-year-old to have." },
      { h: "Living in Korea without really knowing Korea" },
      { p: "There is another layer to this. Classes are taught in English. Friends speak English with one another. The books we read, the news we follow, and the essays we write are all in English. Songdo itself is a planned city with a relatively large international population, so even when we leave school, the atmosphere does not always feel completely different." },
      { p: "It is not that I cannot speak Korean. I speak Korean at home, and I mix Korean and English with my friends. But at some point, I noticed something strange. I can have an everyday conversation in Korean. But when the conversation turns to social issues or the news, I sometimes struggle to speak. Not because I do not know the vocabulary. Because I have never learned to think about those subjects in Korean." },
      { p: "I do not always understand what students my age in Korea are angry about, what they worry about, or what they care about. That leaves me in an awkward position. If I graduate and move to the United States or the United Kingdom, I will be the Korean kid. But when I am in Korea, I can feel slightly out of place. I do not completely belong on either side." },
      { p: "You could call that a privileged complaint. And honestly, it is. Attending an international school is expensive, and it comes with real advantages. I have no intention of denying that. But privilege does not automatically erase every problem. I have received a good education, and at the same time, I have grown up feeling like a guest in the country where I live." },
      { h: "So what?" },
      { p: "I am not suggesting that we need to make some enormous change. Students cannot build a new bridge or add a subway line. But I do think there are things schools can do." },
      { p: "Connections with other schools \u2014 whether international or Korean \u2014 could become real, ongoing programs rather than formal events that happen once a year. Student clubs could reach beyond the school gates instead of existing entirely within them. And Korean language and Korean society could be taught not simply as a foreign-language subject, but as a way of understanding the place where we actually live." },
      { p: "On an individual level, there is also something we can do: go out. Even when it is inconvenient. If you keep putting something off because three hours of travel feels like too much, three years will pass surprisingly quickly. I learned that a little too late." },
      { p: "Songdo is a city beautifully built out of glass. The problem is that glass can be a wall, too. You can see everything on the other side. You just have to walk a long way around to get there." },
    ],
  },

  // ===== MAY 2026 =====
  {
    id: "may-cvs", issue: "2026-05", featured: true,
    cat: "Food",
    title: "Taste of the Korean Convenience Store",
    author: "Songdo Times", org: "Food Desk",
    date: "May 30, 2026", read: 8,
    img: "images/cvs-cover.jpg",
    photo: "Nine convenience-store picks, tested in Songdo",
    dek: "Korea's convenience stores have gone viral \u2014 they are less corner shops than tiny restaurants. In May we tried the drinks, ramens, and snacks you can only find here, and ranked three you might try in each.",
    body: [
      { p: "In May, I explored the most popular convenience store foods in Songdo, ranking three-might-try drinks, ramens, and snacks that are only sold in South Korea. Lately, Korea's convenience stores have gone viral on social media for their unusual snacks, instant noodles, and drinks. Tourists pile in to try food they can't find anywhere else \u2014 and with so many menu items, these stores feel more like small restaurants than ordinary convenience stores." },
      { h: "Three Unique Drinks" },
      { p: "For drinks, I tried viral Banana Milk, only-in-Korea Toreta, and Barley Tea. Each has a different flavor and feel on the way down. Some are sweet and refreshing, others light and healthy \u2014 depending on your taste, one may suit you better than the rest." },
      { review: { img: "images/cvs-banana-milk.jpg", name: "Banana Milk", text: "Banana Milk is uncommon outside Korea and an absolute must. The milky-banana flavor refreshes the palate \u2014 and though I don't even like milk or bananas, I enjoy it. It has a unique taste, unlike ordinary milk or juice, and you'll find it in nearly every store. For visitors, it's a simple taste of Korean food culture." } },
      { review: { img: "images/cvs-toreta.jpg", name: "Toreta", text: "Toreta is like Gatorade or Powerade, but it tastes more like drops of fruit in water. I'd recommend it when you're tired from walking and sweating; its light, refreshing taste makes it easy to drink on hot days. Unlike many sports drinks, it isn't overly sweet \u2014 a big reason people love it after time outdoors." } },
      { review: { img: "images/cvs-barley-tea.jpg", name: "Barley Tea", text: "Barley Tea is very easy to drink, relatively healthy, with no resistance going down. I tend to think drinks are bad for the body \u2014 but this is made of roasted barley. Its mild, refreshing taste suits any time of day, it isn't too sweet, and it works hot or cold." } },
      { h: "Three Spicy Ramens" },
      { p: "For ramen, I tried Samyang Carbo Buldak Bokkeum Myeon, Shin Ramyun, and a slim Cup-noodle. Each has a different mouthfeel, spice level, and flavor \u2014 some rich and creamy, others light and simple \u2014 so there's one for everyone." },
      { review: { img: "images/cvs-cupnoodle.jpg", name: "Noodle-Fit Cup-noodle", text: "The noodles are thin and a little clear; once boiled they tangle up, which can drive you a bit crazy. The taste is similar to normal ramen, but it has far fewer calories \u2014 so there's no guilt in eating it." } },
      { review: { img: "images/cvs-samyang.jpg", name: "Samyang Carbo Buldak Bokkeum Myeon", text: "It can be spicy for many, so it's better with cheese added \u2014 the creamy carbonara flavor balances the heat and makes it more enjoyable. The noodles are chewy and flavorful, which is why so many love it. It's gone popular well beyond Korea; if you enjoy spicy food, it's worth trying." } },
      { review: { name: "Shin Ramyun", text: "Shin Ramyun is the standard \u2014 Korea's most popular instant noodle, often seen as the representative Korean ramen. The noodles are chewy and the broth has a strong taste that pairs well with vegetables, eggs, or other toppings." } },
      { h: "Three Addictive Snacks" },
      { p: "I tried Banana Kick, Marine Boy, and Posstick \u2014 all chips, each with its own crispiness and a different take on saltiness." },
      { review: { img: "images/cvs-posstick.jpg", name: "Posstick", text: "Possticks have a simple taste \u2014 fried potato, in a large size. If you're after a non-irritating snack, try it. It's lightly seasoned, so it's never overwhelming, and its crispy texture pairs well with all kinds of drinks." } },
      { review: { img: "images/cvs-marineboy.jpg", name: "Marine Boy", text: "Marine Boy is salty and addictive, one of Korea's most popular childhood snacks \u2014 people eat it well into adulthood, which is a guarantee in itself. The chips are shaped like sea creatures \u2014 squid, starfish, dolphin, tuna, blowfish, turtle, crab, whale \u2014 and kids love hunting for them. Crispy and savory, it opens up a lot of memories." } },
      { review: { img: "images/cvs-bananakick.jpg", name: "Banana Kick", text: "Banana Kick is a crispy, sweet banana-flavored puff, and a delight to eat. If you need sugar fast, this is your fix. It's hugely popular in Korea for its standout banana flavor, and the crispy texture makes it a favorite while studying, watching videos, or just hanging out." } },
      { h: "Conclusion" },
      { p: "Trying Korean convenience store food made me realize why it's going viral. These aren't just simple snacks \u2014 they're part of the culture. Some were healthier and lighter, others strong and addictive, which made the whole experience more interesting. Most of them are genuinely tasty, and Koreans love it when visitors try them. Give Korean convenience store food a go \u2014 it'll make your trip that much more fun." },
    ],
  },
  {
    id: "may-schools", issue: "2026-05",
    cat: "Education",
    title: "Unaccredited, Not Unwanted",
    author: "Hannah Lee", org: "Songdo Times",
    date: "May 12, 2026", read: 6,
    img: "images/songdo-skyline-hanok.jpg",
    photo: "Songdo's skyline rising behind the Gyeongwonjae hanok village",
    dek: "On April 29, the Ministry of Education announced sweeping new measures to manage Korea's unaccredited international schools. Respect for the decision is due \u2014 but is closing them the right answer, or one made without weighing every perspective?",
    body: [
      { p: "With 7 international schools and about 40 foreign schools, South Korea is pursuing global education. That number sounds large, but the 7 are only the schools formally acknowledged within the Korean education curriculum. Beyond them, a great many unauthorized international schools operate across the country. On April 29, 2026, the Ministry of Education, alongside regional offices, officially announced the \u201cComprehensive Measures to Strengthen the Management of Unaccredited and Unregistered Educational Facilities.\u201d Even as we respect that decision, the question remains: is it the right thing to do, or a poor one that fails to consider the various perspectives?" },
      { h: "Why \u2018unaccredited\u2019 is a problem" },
      { p: "Unaccredited international schools draw scrutiny because of their uncontrolled education programs. These schools are registered as a \u2018hagwon\u2019 \u2014 an after-school support institution \u2014 so their students are not recognized as recipients of Korean education. Even after graduating, it is hard to enroll in a Korean university without taking the Korean GED. Global universities, too, take a dim view of unaccredited schools, since they are not officially recognized as schools at all." },
      { h: "So why do parents still choose them?" },
      { p: "Despite these disadvantages, why do parents send their children to schools labeled \u2018unaccredited\u2019 or \u2018unauthorized\u2019? Because the schools offer real benefits. First, they require less strict entrance requirements than accredited international schools, so parents who want their children to experience a foreign education system can enroll them without extra preparation. And it is the easiest way to begin a foreign education program without leaving the country." },
      { p: "These schools should be controlled by the government \u2014 but not by closing every one of them. Instead, I would suggest creating a standard to evaluate whether a facility is fit to serve as a school." },
      { h: "A proposed standard" },
      { p: "The first standard could be the main school. If an international school is not operated within Korea, it should have a parent school in another country that produces the original education program. Calvin Manitoba International School, for example, has its main school in Manitoba and follows the curriculum from Winnipeg, Canada. Officials from Canada's ministry of education visit each year to check the program and the facilities themselves." },
      { p: "The second standard could be the size of the student body. When an unaccredited school is closed, a great many students lose their school in an instant \u2014 and faculty lose their jobs. So if a school's population exceeds a particular number, it could be permitted to operate. Fayston Preparatory School, for instance, counts more than a thousand students and faculty. Even so, it should still be subject to a check by Korea's ministry of education every month or every year." },
    ],
  },
  {
    id: "may-oil", issue: "2026-05",
    cat: "World",
    title: "The Price of a Distant Strait",
    author: "Hannah Lee", org: "Songdo Times",
    date: "May 24, 2026", read: 5,
    photo: "Fuel prices on the rise \u2014 a global tension felt at the Songdo pump",
    dek: "Tension in the Strait of Hormuz sent oil prices climbing this spring \u2014 and the ripple reached all the way to a liter of milk, a teacher's commute, and a government relief fund.",
    body: [
      { p: "Rising tensions in the Strait of Hormuz disrupted oil shipments and caused oil prices to jump. As the standoff continued, fears of supply problems and higher shipping costs put fresh pressure on global markets. Ceasefire talks calmed prices slightly, but the uncertainty is still affecting fuel costs, inflation, and economic growth worldwide." },
      { h: "How oil becomes inflation" },
      { p: "A higher oil price can also drive inflation, because oil runs through the entire process of making a product. Take a carton of milk that costs 1,000 won. The feed for the cow rises in price along the way, and keeping the cows takes more money. Then, in delivering the milk to market, the driver raises the delivery charge because he is paying more for fuel. Step by step, the price climbs." },
      { p: "An academy teacher who drives to work feels it directly: \u201cWith the rise of oil price, I feel pressure to pay for gas. I used to spend only about 1,800 won per liter, but it has gone up to 2,300 won per liter. It sometimes makes me nervous to check the price.\u201d" },
      { h: "A relief fund \u2014 and its critics" },
      { p: "As a remedy, the Korean government opened applications for a second high-oil-price relief fund. Households in the lower 70% of earners can receive between 100,000 and 600,000 won per person. Seoul Economic Daily reported that first-round applicants totaled 3.075 million \u2014 an application rate of 95.2 percent \u2014 with disbursements of 1.7459 trillion won." },
      { p: "Not everyone is satisfied. Chosun Biz reported complaints over who qualifies and who does not. The government weighs health insurance, workplace- and community-based status, and household size \u2014 a method many feel can sort incomes unfairly." },
      { note: "Reporting draws on Seoul Economic Daily and Chosun Biz coverage of the second high-oil-price relief fund." },
    ],
  },
  {
    id: "may-libraries", issue: "2026-03",
    cat: "City",
    title: "Three Libraries in Songdo: Which One Should You Visit?",
    author: "Hannah Lee", org: "Songdo Times",
    date: "Mar 12, 2026", read: 5,
    img: "images/nuri-library.jpg",
    photo: "Nuri Park Small Library, a hanok-style reading room in Songdo",
    dek: "Last year the Songdo International Library opened \u2014 but it is far from the city's only library. We compared the three, to help you decide where to spend an afternoon with a book.",
    body: [
      { h: "Songdo International Library" },
      { p: "The first library to introduce is the Songdo International Library. It opens at 9 a.m. and closes at 9 p.m. on weekdays, and at 6 p.m. on weekends. As the largest and newest library in Songdo, it offers a wide range of facilities, including a digital zone, community rooms, and an international art hall. It is located at 115-2 Songdo-dong, Yeonsu-gu, Incheon (166 Academy-ro). Due to its popularity, the library can be quite crowded on weekends, and the first floor can be slightly difficult to navigate. Even so, it provides a wide selection of books \u2014 from children's literature to adult collections \u2014 making it one of the best places in Songdo to relax and enjoy reading." },
      { h: "Haedoji Library" },
      { p: "The second library is Haedoji Library, a public library located in Haedoji Park (7 Haedoji-ro, Yeonsu-gu, Incheon). It is closed on Mondays but operates from 9 a.m. to 10 p.m. on weekdays and until 6 p.m. on weekends. Although it is smaller than the Songdo International Library, it still offers a large collection of books. The first floor is dedicated to children and provides a comfortable reading environment, while the second floor is designed for young adults and adults. The library also includes facilities such as toddler programs, a digital zone, and Haedoji Hall. One downside is that the second-floor reading area is relatively small \u2014 but it remains a convenient place to borrow books." },
      { h: "Nuri Park Small Library" },
      { p: "The third library is Nuri Park Small Library, a local library located in Nuri Park (20 Songdo Culture-ro, Yeonsu-gu, Incheon). It is closed on Mondays and Sundays, and operates from 10 a.m. to 6 p.m. on other days. Although it does not have as many books as the Songdo International Library, it still provides a selection suitable for all ages, from toddlers to adults. The library offers a calm and relaxing atmosphere, making it ideal for quiet reading. One of its unique features is its traditional hanok-style design, which blends beautifully with the surrounding natural environment." },
      { h: "So, which one?" },
      { p: "Each library in Songdo has its own strengths. The Songdo International Library is ideal for those who want a modern and spacious place to read. Haedoji Library is convenient for borrowing books and offers a balanced environment for different age groups. Meanwhile, Nuri Park Small Library is perfect for those who prefer a quiet and traditional setting." },
    ],
  },

  // ===== APRIL 2026 =====
  {
    id: "apr-festivals", issue: "2026-04",
    cat: "Culture",
    title: "Spring Festivals and Attractions in Songdo",
    author: "Hannah Lee", org: "Songdo Times",
    date: "Apr 10, 2026", read: 6,
    img: "images/IMG_0756.jpg",
    photo: "Cherry blossoms over Songdo Central Park in spring",
    dek: "Thanks to its expansive infrastructure, Songdo hosts a variety of large-scale events \u2014 especially in spring. Here are the festivals and places worth a spring afternoon.",
    body: [
      { p: "There are several major spring festivals and places to visit in Songdo. Thanks to its expansive infrastructure, Songdo is able to host a variety of large-scale events, especially during the spring season." },
      { h: "Pet Fair" },
      { p: "Date: April 17\u201319 \u00b7 Place: Songdo Convensia. Although it is not specifically a spring festival, the Pet Fair is a great event to enjoy during a spring outing. Visitors can explore the fair with their pets while taking a walk around the area. Admission ranges from 5,000 to 10,000 won, and tickets can be even cheaper if reserved in advance." },
      { h: "Songdo Walk Run Festival" },
      { p: "Date: April 25\u201326, 2026 \u00b7 Place: Songdo Moonlight Festival Park. This festival focuses on health and wellness. Visitors can participate in a variety of activities, including marathons, dog sports, and other athletic events. In addition to sports, there are food trucks offering a wide range of food, as well as camping exhibitions where visitors can purchase equipment at discounted prices. This combination of activities makes it a unique and energetic spring event." },
      { fig: { img: "images/IMG_0754.jpg", cap: "The blossom-lined promenade toward Songdo's Central Park towers." } },
      { h: "Central Park in Spring (April\u2013May)" },
      { p: "Place: Songdo Central Park. Even without large festivals, Central Park is one of the best places to enjoy spring in Songdo. It is perfect for picnics and relaxing outdoor activities. Visitors can ride small boats with friends or family, rent bicycles, and enjoy the beautiful spring flowers. The park also features unique attractions such as deer and a traditional hanok village, making it an ideal destination for a peaceful spring day." },
    ],
  },
  {
    id: "apr-kickboard", issue: "2026-04",
    cat: "City",
    title: "A Rise of No-Kickboard Zones in Songdo",
    author: "Jei Jang", org: "Songdo Times",
    date: "Apr 24, 2026", read: 6,
    img: "images/kickboard-1.jpg",
    photo: "Incheon's new \u2018No-Kickboard Zone\u2019 banners on a Songdo academy street",
    dek: "Electric kickboards became the city's fastest, cheapest ride \u2014 and then its newest danger. This April, Incheon began piloting \u2018No-Kickboard Zones\u2019 in parts of Songdo. Here is why.",
    body: [
      { h: "An introduction to electric scooters" },
      { p: "In recent years, electric kickboards have become a very popular form of transportation in South Korea. Songdo, too, saw heavy use \u2014 but much of it illegal, by teenagers who could make fake ID cards and licenses all too easily." },
      { p: "As the number of kickboards grew, so did concern over accidents. Crashes were reported frequently and complaints from citizens piled up. That is why the Incheon Metropolitan Government introduced a new policy \u2014 \u2018No-Kickboard Zones\u2019 \u2014 in some parts of Songdo." },
      { h: "What is a No-Kickboard Zone?" },
      { p: "In Songdo, the two major no-kickboard zones sit mainly around the academies. A No-Kickboard Zone is a specific area where electric scooters and other personal mobility devices are strictly prohibited, to improve citizens' safety. The policy officially began as a pilot program in April, and the government plans to evaluate its progress by the end of the year." },
      { fig: { img: "images/kickboard-2.jpg", cap: "Green police banners declaring a \u2018No-Kickboard Zone\u2019 hang over a Songdo academy district \u2014 the pilot began in April." } },
      { p: "The reason for the zones is safety. As e-scooters became common, many riders ignored traffic rules \u2014 some rode without helmets, some rode in the roads, some rode without any license at all." },
      { p: "As a result, the number of accidents rose enormously, some of them serious. \u201cElectric scooters can easily lead to serious accidents \u2014 it's dangerous, and everyone should be careful,\u201d explained my friend Grace. As crashes increase, citizens have grown fearful of the scooters." },
      { h: "Accidents in Songdo" },
      { p: "There was a major accident in Songdo involving two middle-school students riding one electric scooter, who collided with a young child's mother. The mother, shielding her daughter, suffered a serious brain injury after being struck by the kickboard. An accident like this should never happen again \u2014 and neither should the smaller ones." },
      { p: "Riders often go without helmets, and scooters are typically used on crowded sidewalks. That combination produces frequent incidents and keeps citizens in danger." },
      { p: "Yet small problems continue: scooters are left scattered across sidewalks, and students ride together without protection. It shows that safety rules remain weak and that similar accidents will recur \u2014 which is exactly why Songdo and other cities are creating No-Kickboard Zones." },
      { h: "How Korea is changing" },
      { p: "Beyond Songdo, many cities now have no-kickboard zones \u2014 especially near Seoul, around academies, and in busy areas. They include Jeju Island, Gyeonggi Province, Seoul, Busan, Incheon, and other regions." },
      { h: "Ideas for more solutions" },
      { p: "The government could focus on stronger ID verification, speed limits, and better parking systems for electric scooters. Stricter rules and better enforcement must be emphasized. There could also be auto-stop restricted zones or built-in speed control \u2014 a simple task for today's technology." },
      { p: "Teenagers are usually the heaviest e-scooter users; more than 60% of subscribers are students. Since people ride for speed, fun, low cost, and easy access, there should be other safe forms of transportation that can absorb that same demand." },
    ],
  },
  {
    id: "apr-hagwon", issue: "2026-04", featured: true,
    cat: "Education",
    title: "Inside Korea's Hagwon Culture",
    author: "Grace Yoo", org: "Calvin Manitoba International School",
    date: "Apr 18, 2026", read: 6,
    img: "images/hagwon-class-web.jpg",
    photo: "An SAT Reading class in session at a Songdo international academy",
    dek: "South Korea ranks among the world's top 15 in education — and much of that learning happens after school, at the \u2018hagwon.\u2019 For families new to Korea, the system can be a mystery. Here is how it works.",
    body: [
      { p: "South Korea is a top-15 country in the world's education ranking. To keep pace with it, most students attend a \u2018hagwon,\u2019 or private academy. But hagwon culture is unfamiliar to many foreigners living and studying in Korea. What exactly is a hagwon, and how does the system work?" },
      { h: "What is a hagwon?" },
      { p: "A hagwon is an institution that provides extra lessons after regular school. Academies are organized by subject \u2014 math, science, English \u2014 and tailor their lessons to different schools. The main goal is to raise students' grades, prepare them for school exams, and help with college admissions. Because international schools follow a different curriculum, international students attend specialized hagwons of their own." },
      { h: "A hagwon for international students" },
      { p: "One example is Soop International Academy, located at 161 Sinsong-ro, Yeonsu-gu, Incheon (The Heights, Suite 409). It covers math, English, and science for grades 1 through 12, running about fifteen classes across the three subjects \u2014 from Pre-Algebra and AMC 10 to IB English and Grade 10 Biology \u2014 plus seasonal programs over the winter, summer, and spring breaks. Every class is led by an experienced teacher." },
      { h: "How to apply" },
      { steps: [
        "Call the academy at 032-832-6506 and tell them your child's grade and school \u2014 for example, \u201cMy daughter is in 5th grade at Happy International School.\u201d A counselor will walk you through the process.",
        "Set a date for a level test and an in-person counseling session.",
        "Take the level test, choose the class that best fits your student, and pay the tuition.",
      ] },
      { h: "What parents and staff say" },
      { qa: [
        { q: "What is special about this academy?", a: "We focus on being a small-group, elite academy. We provide customized lessons tailored to each student's individual goals, and we support their extracurriculars according to those objectives." },
        { q: "What is your motto?", a: "\u201cYour bridge to academic excellence.\u201d Academy Soop aims to be the bridge that helps students reach their university goals." },
        { q: "What are your educational values?", a: "We don't recommend an excessive number of subjects. We suggest only the essential classes that align with a student's target major \u2014 minimizing unnecessary coursework to maximize efficiency." },
        { q: "What makes you different?", a: "Many academies charge high fees for extracurricular consulting. For our enrolled students, we don't charge separately for that \u2014 only for actual instructional time, which I believe sets us apart." },
      ] },
      { p: "One parent summed it up simply: \u201cThe academy teaches only a few students at a time, so it helps my daughters understand the details better. And the study room inside means they can study any time. Yes \u2014 I really like it!\u201d" },
    ],
  },

  // ===== MARCH 2026 =====
  {
    id: "mar-gtx", issue: "2026-03", featured: true,
    cat: "City",
    title: "The GTX Is Coming to Songdo",
    author: "Jason Song", org: "Chadwick International School",
    date: "Mar 4, 2026", read: 5,
    img: "images/songdo-traffic-web.jpg",
    photo: "A Songdo intersection \u2014 the daily commute the GTX aims to transform",
    dek: "A high-speed commuter railway promises to cut the trip from Songdo to Seoul from 90 minutes to as little as 20. Here is what the GTX means for the city.",
    body: [
      { p: "The GTX (Great Train eXpress) is a high-speed commuter rail system designed to connect major cities and suburbs to Seoul far faster than the existing metro. It is a national infrastructure project led by the South Korean government to cut commute times and improve transport across the Seoul metropolitan area. Reaching speeds of up to 180 km/h, it can carry passengers to Seoul faster than ever before." },
      { h: "Six lines, one network" },
      { p: "The GTX is planned as six lines in total \u2014 A, B, C, D, E, and F. So far only Line A is partially open, running between Dongtan and Suseo and on the northern stretch from Unjeong to Seoul Station. The central section from Seoul Station to Suseo, including Samseong Station, has not been built yet, but it is expected to open in stages between this year and 2028." },
      { h: "Why Line B matters for Songdo" },
      { p: "Line B is the most important for Songdo residents. It begins at Incheon National University Station in the 1st development district, then heads east \u2014 stopping at Incheon City Hall, Bupyeong, Bucheon, Sindorim, Yeouido, Yongsan, Seoul Station, Cheongnyangni, and Sangbong \u2014 before continuing northeast all the way to Maseok Station in Namyangju, Gyeonggi Province." },
      { p: "Today the trip to Seoul takes about an hour and a half by public transport. With the GTX, the government hopes to cut that to 20\u201330 minutes. The project faced obstacles, but it has officially begun, with construction expected to finish by 2031. It is a long wait \u2014 but once it is done, getting around from Songdo will be easier than ever." },
      { note: "Reporting drawn from Busan Ilbo, Incheon.go.kr, Railway Gazette International, Dong-A Ilbo, and Asiae (2024\u20132025)." },
    ],
  },
  {
    id: "mar-dujjonku", issue: "2026-03",
    cat: "Food",
    title: "Du-jjon-Ku",
    author: "Grace Yoo", org: "Calvin Manitoba International School",
    date: "Mar 18, 2026", read: 5,
    img: "images/dujjonku-tomoroo.jpg",
    photo: "Du-jjon-Ku \u2014 the Dubai-style chocolate-and-pistachio cookie sweeping Songdo's bakeries",
    dek: "Teenagers can't stop talking about Du-jjon-Ku, and the craze has reached Songdo \u2014 more than 30 shops now sell it. So what is this tiny, pricey dessert, and why is everyone obsessed?",
    body: [
      { p: "Songdo, Incheon \u2014 teenagers are obsessed with Du-jjon-Ku, and the craze is spreading across Songdo, where more than thirty places now sell it. Du-jjon-Ku is a trending K-dessert made of marshmallow, chocolate, pistachio, and kadaif. The kadaif is mixed with pistachio spread, then wrapped in marshmallow and dusted with cocoa powder. One small piece costs about 7,000\u20138,000 won. How did such a tiny dessert get so popular \u2014 and so expensive?" },
      { h: "Why so popular \u2014 and so pricey?" },
      { p: "The ingredients cost about 2,940 won. At a selling price near 7,500 won, that is a cost rate of 39.2% \u2014 and since most desserts run 20\u201330%, Du-jjon-Ku is actually quite reasonable. That value, paired with the \u2018small luxury\u2019 trend, is what sent it viral. The name says it all: Du-jjon-Ku is short for \u2018Dubai JJon-deuk Cookie\u2019 \u2014 \u2018Dubai\u2019 for luxury and money, and \u2018JJon-deuk\u2019 for its signature chewy texture." },
      { h: "How to get your hands on one" },
      { p: "It is simple, but it takes timing. Find a shop that sells Du-jjon-Ku and check its hours \u2014 Tomoroo Bakery, for instance, is open 8:00 to 21:30. Be aware there may be a limit per person. The real challenge is timing: it is popular nationwide and sells out fast, so you may not succeed on the first try. But keep at it and you will get one \u2014 who knows, you might even become a Du-jjon-Ku master." },
      { h: "Taste test: Tomoroo vs. Bread Tour" },
      { p: "For accurate intel, we interviewed an Incheon local who tried Du-jjon-Ku from both Tomoroo Bakery and Bread Tour." },
      { qa: [
        { q: "What were the big differences between the two?", a: "The price, first \u2014 Tomoroo is about 1,000 won more expensive. And the flavor is slightly different; Bread Tour's is a bit sweeter." },
        { q: "How did you come to try it? Do you like it?", a: "I tried it because of the trend. At first I didn't love it \u2014 it wasn't sweet enough. But on a second try I really enjoyed it. I could eat several at once because it isn't too sweet, and the unique texture won me over." },
        { q: "So \u2014 Tomoroo or Bread Tour?", a: "It's case by case, but I enjoyed Bread Tour more. Both are fantastic, though." },
      ] },
      { h: "Where to find Du-jjon-Ku in Songdo" },
      { places: [
        { name: "Tomoroo Bakery", addr: "Haedoji-ro 120beon-gil, Yeonsu-gu, Incheon", hours: "8:00 \u2013 21:30", img: "images/dujjonku-tomoroo.jpg" },
        { name: "ANS Bakery", addr: "160 Central-ro, Yeonsu-gu, Incheon", hours: "8:00 \u2013 23:00", img: "images/dujjonku-ans.jpg" },
      ] },
    ],
  },
];
